### ISSUE TITLE
Hey man I need ur help!

### ISSUE THREAD

**Issue by maxinimize** [BrunoCode/hmk3#1]
https://gist.github.com/nperez0111/f82d1399504d0de218c22b81317e8f02#gistcomment-2130761

I tried this, but I got nothing,

I saw u said it worked for u 14 hrs ago. Can u help me?  Thanks in advance!

**Comment by BrunoCode** [comment]
hey yes this works on the site. works in google chrome. just visit the page that contains some of your images. go to dev console on chrome, paste code, press enter, a new page will open and it will have many images, most watermarked.
